const icons={dashboard:'◫',purchase:'⇩',inventory:'⇩',stock:'▦',orders:'▤',shipping:'➤',products:'◇'};
const state={page:'dashboard',products:[],query:'',modal:null,orderTab:'全部',inventoryFilter:'全部'};
const store={
  get(k,d){try{return JSON.parse(localStorage.getItem('trueerp_'+k))??d}catch{return d}},
  set(k,v){localStorage.setItem('trueerp_'+k,JSON.stringify(v))}
};
const fmt=n=>new Intl.NumberFormat('zh-CN').format(n);
const days=d=>Math.ceil((new Date(d)-new Date())/86400000);
const today=()=>new Date().toISOString().slice(0,10);
const plusDays=n=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

const demoOrders=[
 {id:'JY202608130014',time:'2026-08-13 09:42:18',channel:'加拿大天猫直购',buyer:'王**',sku:'CA068958027135',name:'NATURAL FACTORS 褪黑素（1mg-90片）',qty:2,status:'待发货',tracking:''},
 {id:'JY202608130009',time:'2026-08-13 08:15:06',channel:'加拿大天猫直购',buyer:'林**',sku:'CA068958010601',name:'NATURAL FACTORS 维生素D（1000IU - 500粒软胶囊）',qty:1,status:'待审核',tracking:''},
 {id:'JY202608120088',time:'2026-08-12 19:31:42',channel:'加拿大天猫直购',buyer:'陈**',sku:'CA854378001486',name:'CANPREV 甘氨酸锌 25毫克（120粒胶囊）',qty:1,status:'拣货中',tracking:''},
 {id:'JY202608110006',time:'2026-08-11 04:15:01',channel:'加拿大天猫直购',buyer:'赵**',sku:'CA068958027135',name:'NATURAL FACTORS 褪黑素（1mg-90片）',qty:1,status:'已发货',tracking:'LP00836237478802'}
];
const demoBatches=[
 {id:'B20260813001',sku:'CA068958027135',name:'NATURAL FACTORS 褪黑素（1mg-90片）',warehouse:'加拿大多伦多1号仓',qty:126,locked:3,production:'2026-05-08',expiry:'2028-05-07'},
 {id:'B20260722002',sku:'CA068958010601',name:'NATURAL FACTORS 维生素D（1000IU - 500粒软胶囊）',warehouse:'加拿大多伦多1号仓',qty:84,locked:1,production:'2025-12-10',expiry:'2027-12-09'},
 {id:'B20260618001',sku:'CA854378001486',name:'CANPREV 甘氨酸锌 25毫克（120粒胶囊）',warehouse:'加拿大多伦多1号仓',qty:48,locked:1,production:'2025-08-20',expiry:plusDays(72)},
 {id:'B20260409003',sku:'CA733739814104',name:'加拿大版 NOW硼（3毫克-100粒蔬菜胶囊）',warehouse:'加拿大多伦多1号仓',qty:16,locked:0,production:'2025-03-02',expiry:plusDays(25)}
];
let orders=store.get('orders',demoOrders),batches=store.get('batches',demoBatches),receipts=store.get('receipts',[]);

function nav(){return `<aside class="sidebar"><div class="brand"><b class="brand-mark">T</b><span>TrueERP<small>跨境电商管理系统</small></span></div><div class="nav-label">工作台</div>${[['dashboard','经营概览'],['products','产品管理'],['purchase','采购管理'],['stock','库存管理'],['orders','订单管理'],['shipping','发货管理']].map(([k,v])=>`<button class="nav-item ${state.page===k?'active':''}" data-page="${k}"><span class="nav-icon">${icons[k]}</span><span>${v}</span></button>`).join('')}</aside>`}
function header(){const title={dashboard:'经营概览',purchase:'采购入库',inventory:'采购入库',stock:'库存管理',orders:'订单管理',shipping:'发货管理',products:'产品管理'}[state.page];return `<header class="topbar"><div class="breadcrumb">TrueERP&nbsp; / &nbsp;${title}</div><div class="top-actions"><span>⌕</span><span>◯</span><span>帮助</span><div class="avatar">M</div></div></header>`}
function layout(body){return `<div class="shell">${nav()}<main class="main">${header()}<section class="content">${body}</section></main></div>${state.modal?modal():''}`}
function pageHead(title,sub,action=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function statusTag(s){const cls=s.includes('已')?'green':s.includes('待')?'orange':s.includes('临期')?'red':'blue';return `<span class="tag ${cls}">${s}</span>`}
function dashboard(){const total=batches.reduce((s,b)=>s+b.qty,0),locked=batches.reduce((s,b)=>s+b.locked,0),pending=orders.filter(o=>o.status==='待发货').length,near=batches.filter(b=>days(b.expiry)<=90).length;return `${pageHead('经营概览','库存、订单和履约状态一目了然')}<div class="kpis">${[['现有库存',fmt(total)+' 件','较昨日 +12','▦'],['待处理订单',orders.filter(o=>!o.status.includes('已')).length+' 单','实时同步','▤'],['待发货',pending+' 单','请及时处理','➤'],['临期批次',near+' 批','90 天内到期','!']].map(x=>`<div class="card kpi"><div class="kpi-top"><span>${x[0]}</span><i class="kpi-icon">${x[3]}</i></div><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('')}</div><div class="grid-2"><div class="card"><div class="panel-head"><h3>近 7 日订单趋势</h3><span class="muted">订单量</span></div><div class="chart">${[42,62,45,76,58,92,68].map((h,i)=>`<div class="bar-group"><div class="bar" style="--h:${h*2}px"></div>${['周五','周六','周日','周一','周二','周三','今天'][i]}</div>`).join('')}</div></div><div class="card"><div class="panel-head"><h3>库存预警</h3><span class="link" data-page="inventory">查看全部</span></div><div class="alerts">${batches.slice().sort((a,b)=>days(a.expiry)-days(b.expiry)).slice(0,4).map(b=>`<div class="alert"><i class="alert-dot"></i><div><b>${esc(b.name)}</b><div class="muted">${b.id} · ${days(b.expiry)} 天后到期 · 可用 ${b.qty-b.locked}</div></div></div>`).join('')}</div></div></div>`}
function productsPage(){let list=state.products.filter(p=>!state.query||Object.values(p).some(v=>String(v).toLowerCase().includes(state.query.toLowerCase())));return `${pageHead('产品管理','产品字段完全沿用原始货品 Excel',`<button class="btn primary" data-action="addProduct">＋ 新增产品</button>`)}<div class="toolbar"><div class="search"><input id="search" value="${esc(state.query)}" placeholder="搜索货品编号、名称、品牌或条码"></div><select id="brandFilter"><option>全部品牌</option>${[...new Set(state.products.map(p=>p.品牌))].filter(Boolean).slice(0,30).map(x=>`<option>${esc(x)}</option>`).join('')}</select><button class="btn">导出</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>货品编号</th><th>货品名称</th><th>分类</th><th>品牌</th><th>基础单位</th><th>规格</th><th>条码</th><th>重量(g)</th><th>操作</th></tr></thead><tbody>${list.slice(0,100).map(p=>`<tr><td class="mono">${p.货品编号}</td><td class="name-cell">${esc(p.货品名称)}</td><td>${p.分类}</td><td>${p.品牌}</td><td>${p.基础单位}</td><td>${p.规格}</td><td class="mono">${p.条码}</td><td>${p['重量(g)']}</td><td><button class="icon-btn link" data-edit-product="${p.id}">编辑</button></td></tr>`).join('')}</tbody></table></div><div class="footer-row"><span>显示前 ${Math.min(100,list.length)} 条</span><span>共 ${fmt(list.length)} 条产品</span></div></div>`}
function inventoryPage(){let list=batches.filter(b=>state.inventoryFilter==='全部'||(state.inventoryFilter==='临期'&&days(b.expiry)<=90)||(state.inventoryFilter==='正常'&&days(b.expiry)>90));return `${pageHead('库存管理','按仓库与批次管理库存，支持保质期预警',`<button class="btn primary" data-page="purchase">＋ 采购入库</button>`)}<div class="status-tabs">${['全部','正常','临期'].map(x=>`<button class="tab ${state.inventoryFilter===x?'active':''}" data-inv-tab="${x}">${x}</button>`).join('')}</div><div class="card"><div class="table-wrap"><table><thead><tr><th>批次号</th><th>货品编号</th><th>货品名称</th><th>仓库</th><th>库存量</th><th>锁定</th><th>可用</th><th>生产日期</th><th>有效期至</th><th>剩余保质期</th><th>状态</th></tr></thead><tbody>${list.map(b=>{const d=days(b.expiry);return `<tr><td class="mono">${b.id}</td><td class="mono">${b.sku}</td><td class="name-cell">${esc(b.name)}</td><td>${b.warehouse}</td><td>${b.qty}</td><td>${b.locked}</td><td><b>${b.qty-b.locked}</b></td><td>${b.production}</td><td>${b.expiry}</td><td>${d} 天</td><td>${statusTag(d<=90?'临期预警':'正常')}</td></tr>`}).join('')}</tbody></table></div><div class="footer-row"><span>库存分配建议：FEFO（先到期先出）</span><span>共 ${list.length} 个批次</span></div></div>`}
function purchasePage(){return `${pageHead('采购入库','创建采购收货单并生成库存批次',`<button class="btn primary" data-action="newReceipt">＋ 新建入库单</button>`)}<div class="filter-layout"><div class="card filter-panel"><div class="filter-title">筛选</div><div class="field"><label>收货仓库</label><select><option>全部仓库</option><option>加拿大多伦多1号仓</option></select></div><div class="field"><label>入库日期</label><input type="date"></div><div class="field"><label>供应商</label><input placeholder="输入供应商"></div><button class="btn primary" style="width:100%">筛选</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>入库单号</th><th>货品编号</th><th>货品名称</th><th>入库量</th><th>仓库</th><th>生产日期</th><th>有效期至</th><th>入库日期</th><th>状态</th></tr></thead><tbody>${receipts.length?receipts.map(r=>`<tr><td class="mono">${r.id}</td><td>${r.sku}</td><td class="name-cell">${esc(r.name)}</td><td>${r.qty}</td><td>${r.warehouse}</td><td>${r.production}</td><td>${r.expiry}</td><td>${r.date}</td><td>${statusTag('已入库')}</td></tr>`).join(''):`<tr><td colspan="9"><div class="empty">暂无入库记录，点击“新建入库单”开始</div></td></tr>`}</tbody></table></div></div></div>`}
function ordersPage(){let list=orders.filter(o=>state.orderTab==='全部'||o.status===state.orderTab);return `${pageHead('订单管理','天猫直购订单集中处理',`<button class="btn primary" data-action="sync">↻ 同步天猫订单</button>`)}<div class="status-tabs">${['全部','待审核','待发货','拣货中','已发货'].map(x=>`<button class="tab ${state.orderTab===x?'active':''}" data-order-tab="${x}">${x}</button>`).join('')}</div><div class="toolbar"><div class="search"><input placeholder="搜索订单号、货品或物流单号"></div><span class="muted">最近同步：刚刚</span></div><div class="card"><div class="table-wrap"><table><thead><tr><th>订单号</th><th>下单时间</th><th>销售渠道</th><th>买家</th><th>货品编号</th><th>货品名称</th><th>数量</th><th>订单状态</th><th>物流单号</th><th>操作</th></tr></thead><tbody>${list.map(o=>`<tr><td class="mono link">${o.id}</td><td>${o.time}</td><td>${o.channel}</td><td>${o.buyer}</td><td class="mono">${o.sku}</td><td class="name-cell">${esc(o.name)}</td><td>${o.qty}</td><td>${statusTag(o.status)}</td><td class="mono">${o.tracking||'-'}</td><td>${o.status==='待发货'?`<button class="btn" data-ship="${o.id}">发货</button>`:'-'}</td></tr>`).join('')}</tbody></table></div><div class="footer-row"><span>共 ${list.length} 条订单</span><span>天猫接口：模拟模式</span></div></div>`}
function shippingPage(){const list=orders.filter(o=>o.status==='已发货');return `${pageHead('发货管理','打包、录入物流单号并回传平台')}<div class="toolbar"><div class="search"><input placeholder="搜索订单号或物流单号"></div><button class="btn">打印面单</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>发货时间</th><th>订单号</th><th>物流公司</th><th>物流单号</th><th>货品</th><th>数量</th><th>发货仓库</th><th>平台回传</th></tr></thead><tbody>${list.map(o=>`<tr><td>${o.shippedAt||o.time}</td><td class="mono">${o.id}</td><td>Canada Post</td><td class="mono link">${o.tracking}</td><td>${esc(o.name)}</td><td>${o.qty}</td><td>加拿大多伦多1号仓</td><td>${statusTag('已回传')}</td></tr>`).join('')}</tbody></table></div></div>`}
function modal(){if(state.modal==='receipt')return `<div class="modal-backdrop"><form class="modal" id="receiptForm"><div class="modal-head"><h2>新建采购入库单</h2><button type="button" class="close" data-close>×</button></div><div class="form-grid"><div class="field full"><label>选择产品</label><select name="sku" required>${state.products.slice(0,490).map(p=>`<option value="${p.货品编号}">${p.货品编号} · ${esc(p.货品名称)}</option>`).join('')}</select></div><div class="field"><label>入库数量</label><input name="qty" type="number" min="1" value="1" required></div><div class="field"><label>收货仓库</label><select name="warehouse"><option>加拿大多伦多1号仓</option></select></div><div class="field"><label>生产日期</label><input name="production" type="date" required></div><div class="field"><label>有效期至</label><input name="expiry" type="date" required></div><div class="field full"><label>供应商</label><input name="supplier" value="青岛船长家网络技术有限公司"></div></div><div class="modal-foot"><button type="button" class="btn" data-close>取消</button><button class="btn primary">确认入库</button></div></form></div>`;if(state.modal?.type==='ship')return `<div class="modal-backdrop"><form class="modal" id="shipForm"><div class="modal-head"><h2>订单打包发货</h2><button type="button" class="close" data-close>×</button></div><div class="form-grid"><div class="field full"><label>订单号</label><input value="${state.modal.id}" disabled></div><div class="field"><label>物流公司</label><select name="carrier"><option>Canada Post</option><option>UPS</option><option>FedEx</option></select></div><div class="field"><label>物流单号</label><input name="tracking" required placeholder="扫描或输入物流单号"></div><div class="field full"><label>发货备注</label><input name="note" placeholder="选填"></div></div><div class="modal-foot"><button type="button" class="btn" data-close>取消</button><button class="btn success">确认发货并回传</button></div></form></div>`;return ''}
function render(){let body={dashboard:dashboard,purchase:purchasePage,inventory:inventoryPage,stock:inventoryPage,orders:ordersPage,shipping:shippingPage,products:productsPage}[state.page]();document.querySelector('#app').innerHTML=layout(body);bind();queueMicrotask(()=>window.erpWorkflowAfterRender?.())}
function bind(){document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{state.page=x.dataset.page;render()});document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>{state.modal=null;render()});document.querySelector('[data-action="newReceipt"]')?.addEventListener('click',()=>{state.modal='receipt';render()});document.querySelector('[data-action="sync"]')?.addEventListener('click',()=>{alert('已连接天猫直购模拟接口，本次没有新订单。正式 API 凭证配置后可实时增量同步。')});document.querySelectorAll('[data-order-tab]').forEach(x=>x.onclick=()=>{state.orderTab=x.dataset.orderTab;render()});document.querySelectorAll('[data-inv-tab]').forEach(x=>x.onclick=()=>{state.inventoryFilter=x.dataset.invTab;render()});document.querySelector('#search')?.addEventListener('input',e=>{state.query=e.target.value;render()});document.querySelectorAll('[data-ship]').forEach(x=>x.onclick=()=>{state.modal={type:'ship',id:x.dataset.ship};render()});document.querySelector('#receiptForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),p=state.products.find(p=>p.货品编号===f.get('sku')),id='RK'+Date.now().toString().slice(-10),batch={id:'B'+Date.now().toString().slice(-10),sku:p.货品编号,name:p.货品名称,warehouse:f.get('warehouse'),qty:+f.get('qty'),locked:0,production:f.get('production'),expiry:f.get('expiry')};batches.unshift(batch);receipts.unshift({...batch,id,date:today()});store.set('batches',batches);store.set('receipts',receipts);state.modal=null;render()});document.querySelector('#shipForm')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),o=orders.find(x=>x.id===state.modal.id);o.status='已发货';o.tracking=f.get('tracking');o.shippedAt=new Date().toLocaleString('zh-CN',{hour12:false});store.set('orders',orders);state.modal=null;state.page='shipping';render()})}
fetch('/public/data/products.json').then(r=>r.ok?r.json():fetch('data/products.json').then(x=>x.json())).then(p=>{state.products=p;render()}).catch(()=>fetch('data/products.json').then(r=>r.json()).then(p=>{state.products=p;render()}).catch(()=>{state.products=[];render()}));

// 产品主数据的轻量新增/编辑；保留 Excel 原字段并持久化到当前浏览器。
document.addEventListener('click',event=>{
  const add=event.target.closest('[data-action="addProduct"]');
  const edit=event.target.closest('[data-edit-product]');
  if(!add&&!edit)return;
  const current=edit?state.products.find(p=>p.id===edit.dataset.editProduct):null;
  const code=prompt('货品编号',current?.货品编号||''); if(code===null||!code.trim())return;
  const name=prompt('货品名称',current?.货品名称||''); if(name===null||!name.trim())return;
  const barcode=prompt('条码',current?.条码||'')??'';
  const brand=prompt('品牌',current?.品牌||'')??'';
  const product=current||{id:`P${Date.now()}`,分类:'保健品',ABC分类:'',基础单位:'瓶',换算率:1,货主:'青岛船长家网络技术有限公司',序号:0,规格编号:'',规格:'默认规格',重量:0,重量单位:'g','重量(g)':0};
  Object.assign(product,{货品编号:code.trim(),货品名称:name.trim(),条码:barcode.trim(),品牌:brand.trim()});
  if(!current)state.products.unshift(product);
  store.set('products',state.products);render();
});
